# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98a447cb879e20c3bef9ed523c4f77fe3cdfdb833f1d797577ec3b401ae911c4a1251a07a593c74967409cfa08076962a316b85e158c3266e86cf2bf42261521

test:
  secret_key_base: 9bee51e35c3323fc5a3d40dedaca5f41108c5e93f6d86caadeaa7c862fd5ff199b16a30bd998554ba30caf251b576d6d81b6ade7dc92f31333077dc75de2e8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
